apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eh3ttvws8-dotnet-basic 
  janus-idp.io/tekton: eh3ttvws8-dotnet-basic
  backstage.io/kubernetes-id: eh3ttvws8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh3ttvws8-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  